<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>NINA.Plugin.Livestack</RootNamespace>
    <AssemblyName>nina.plugin.livestack</AssemblyName>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AssemblyTitle>Livestack</AssemblyTitle>
    <Title>Livestack</Title>
    <Authors>Stefan Berg @isbeorn</Authors>
    <Product>Livestack</Product>
    <Description>**CUSTOM FORK** Live stacking within N.I.N.A.</Description>
    <Copyright>Copyright ©  2024-2025</Copyright>
    <Version>1.0.2.0</Version>
    <AssemblyVersion>1.0.2.0</AssemblyVersion>
    <FileVersion>1.0.2.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="NINA.Plugin" Version="3.2.0.1018-nightly" />
  </ItemGroup>
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="&#xD;&#xA;if not exist &quot;%25localappdata%25\NINA\Plugins\3.0.0&quot; (&#xD;&#xA;  echo &quot;Creating $(PlatformName) Plugins folder&quot;&#xD;&#xA;  mkdir &quot;%25localappdata%25\NINA\Plugins\3.0.0&quot;&#xD;&#xA;)&#xD;&#xA;if not exist &quot;%25localappdata%25\NINA\Plugins\3.0.0\$(TargetName)&quot; (&#xD;&#xA;  echo &quot;Creating $(PlatformName) Plugins Livestack folder&quot;&#xD;&#xA;  mkdir &quot;%25localappdata%25\NINA\Plugins\3.0.0\Livestack&quot;&#xD;&#xA;)&#xD;&#xA;&#xD;&#xA;echo &quot;Copying $(PlatformName) $(TargetFileName)&quot;&#xD;&#xA;xcopy &quot;$(TargetPath)&quot; &quot;%25localappdata%25\NINA\Plugins\3.0.0\Livestack&quot; /h/i/c/k/e/r/y&#xD;&#xA;&#xD;&#xA;copy &quot;$(TargetDir)MathNet.Numerics.dll&quot; &quot;%25localappdata%25\NINA\Plugins\3.0.0\Livestack\MathNet.Numerics.dll&quot; /Y&#xD;&#xA;&#xD;&#xA;  " IgnoreExitCode="true" />
  </Target>
</Project>